[build-system]
requires = ["flit_core >=3.2,<4", "wheel"]
build-backend = "flit_core.buildapi"

[project]
name = "lolcatfigletgnuplotprint"
description = "A simple commandline output utility package for printing simple messages and linear xy-plot data with colours and style."
version = "0.0.3"
readme = "README.md"
authors = [{ name = "Lassi Piironen", email = "lsipii@kapsi.fi" }]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "sh==1.14.2",
    "termplotlib==0.3.9",
    "python-dateutil==2.8.2",
    "click==8.1.3"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pip-tools", "unittest"]

[project.urls]
Homepage = "https://github.com/lsipii/lolcatfigletgnuplotprint"

[project.scripts]
lolcatfigletgnuplotprint = "lolcatfigletgnuplotprint.__main__:main"
