[tool.poetry]
name = "catenabible"
version = "1.1.1"
description = ""
authors = ["numbergazing <hello@numbergazing.com>"]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Natural Language :: English"
]

[tool.poetry.scripts]
catena = "catena.__main__:catena"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.0"
beautifulsoup4 = "^4.11.1"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
