[tool.poetry]
name = "configcafe"
version = "0.1.1"
description = "Welcome to the config cafe!"
authors = ["J 'Indi' Harrington"]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.4.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.3.0"
pre-commit = "^2.19.0"
coverage = "^6.4.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
