[tool.poetry]
name = "data-connectors"
version = "0.20.2"
description = ""
authors = ["CA Lee <flowstate_crypto@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyodbc = "^4.0.32"
python-dotenv = "^0.20.0"
SQLAlchemy = "^1.4.37"
pandas = "^1.4.2"
pygsheets = "^2.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"