[tool.poetry]
name = "declarative_argparse"
version = "0.0.4"
description = "A simple wrapper around argparse to permit declarative construction and argument retrieval."
authors = ["Rob Nelson <nexisentertainment@gmail.com>"]
readme="README.md"
repository="https://gitlab.com/N3X15/declarative_argparse"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
mypy = "^0.961"
autopep8 = "^1.6.0"
isort = "^5.10.1"
poetryup = "^0.8.0"
twine = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
